const productData = [
  {
    id: 1,
    category: "사료",
    name: "더리얼 그레인프리 크런치 닭고기 어덜트 1.6kg",
    image: "./images/bestItem01.jpeg",
    sale: 20,
    price: 26400,
    rate: 4.5,
    review: 500,
  },
  {
    id: 2,
    category: "사료",
    name: "네츄럴코어 독 건강한 화식쁘띠 키친 까르보나라 85g",
    image: "./images/bestItem02.jpeg",
    sale: 20,
    price: 2300,
    rate: 4.5,
    review: 75,
  },
  {
    id: 3,
    category: "사료",
    name: "스텔라앤츙스 독 케이지프리 치킨스튜 311g",
    image: "./images/bestItem03.jpeg",
    price: 9500,
    rate: 4.9,
    review: 500,
  },
  {
    id: 4,
    category: "사료",
    name: "페디그리 독 쇠고기 캔 700g",
    image: "./images/bestItem04.jpeg",
    sale: 15,
    price: 3500,
    rate: 4.9,
    review: 102,
  },
  {
    id: 5,
    category: "영양제",
    name: "베스트 프라이스 하루영양3종[모음]",
    image: "./images/hotNu01.webp",
    sale: 50,
    price: 5900,
    rate: 4.9,
    review: 392,
  },
  {
    id: 6,
    category: "영양제",
    name: "닥터레버 듀얼프로 유산균 60g(2gx30p)",
    image: "./images/hotNu02.webp",
    sale: 34,
    price: 23000,
    rate: 4.9,
    review: 32,
  },
  {
    id: 7,
    category: "영양제",
    name: "베스트 프라이스 푸푸루틴 유산균 2g*30p",
    image: "./images/hotNu03.webp",
    sale: 54,
    price: 4580,
    rate: 4.9,
    review: 98,
  },
  {
    id: 8,
    category: "영양제",
    name: "메가파이브 닭 체력강화 50g",
    image: "./images/hotNu04.webp",
    sale: 36,
    price: 3200,
    rate: 4.9,
    review: 82,
  },
  {
    id: 9,
    category: "간식",
    name: "펫라벨 멍쮸쮸 짜먹는 강아지간식 닭가슴살 30gx10개",
    image: "./images/poTreat01.png",
    sale: 35,
    price: 6400,
    rate: 4.0,
    review: 10,
  },
  {
    id: 10,
    category: "간식",
    name: "펫라벨 보양비법 전복 보양죽(닭가슴살+황태+굴)1000g",
    image: "./images/poTreat02.png",
    sale: 10,
    price: 1800,
    rate: 4.5,
    review: 95,
  },
  {
    id: 11,
    category: "간식",
    name: "펫라벨 보양비법 삼계 보양죽(인삼+황태+굴)100g",
    image: "./images/poTreat03.png",
    sale: 10,
    price: 1800,
    rate: 4.5,
    review: 112,
  },
  {
    id: 12,
    category: "간식",
    name: "펫라벨 보양비법 소고기 보양죽(황태+매생이+닭가슴살)100g",
    image: "./images/poTreat04.png",
    sale: 15,
    price: 3900,
    rate: 4.9,
    review: 102,
  },
  {
    id: 13,
    category: "위생미용",
    name: "도기맨 허니스마일 발톰깎이",
    image: "./images/beauty01.jpg",
    sale: 28,
    price: 6500,
    rate: 4.5,
    review: 17,
  },
  {
    id: 14,
    category: "위생미용",
    name: "페디슨 덴탈케어 마이크로 칫솔",
    image: "./images/beauty02.jpg",
    sale: 40,
    price: 1500,
    rate: 4.5,
    review: 29,
  },
  {
    id: 15,
    category: "위생미용",
    name: "쏘아베 핑크 발톱깎이 뺸치형",
    image: "./images/beauty03.jpg",
    sale: 36,
    price: 3900,
    rate: 4.9,
    review: 19,
  },
  {
    id: 16,
    category: "위생미용",
    name: "수퍼펫 러브러브 글러브",
    image: "./images/beauty04.jpg",
    sale: 21,
    price: 5900,
    rate: 4.9,
    review: 332,
  },
  {
    id: 17,
    category: "장난감",
    name: "수퍼펫 러브러브 글러브",
    image: "./images/toy01.webp",
    sale: 26,
    price: 6300,
    rate: 4.5,
    review: 110,
  },
  {
    id: 18,
    category: "장난감",
    name: "펫톤 꽈배기 스틱 터그토이 핑크",
    image: "./images/toy02.webp",
    sale: 14,
    price: 4200,
    rate: 4.5,
    review: 68,
  },
  {
    id: 19,
    category: "장난감",
    name: "펫모닝 스쿼드 덴탈토이 [색상랜덤]",
    image: "./images/toy03.jpg",
    sale: 7,
    price: 2800,
    rate: 4.8,
    review: 58,
  },
  {
    id: 20,
    category: "장난감",
    name: "[무료배송]딩동펫 반려동물 삐삐인형",
    image: "./images/toy04.jpg",
    sale: 10,
    price: 9000,
    rate: 4.5,
    review: 92,
  },
  {
    id: 21,
    category: "산책용품",
    name: "플라워 비프 스케이프",
    image: "./images/hanes32.webp",
    sale: 20,
    price: 11000,
    rate: 4.9,
    review: 79,
  },
  {
    id: 22,
    category: "산책용품",
    name: "데이지 하네스 리드줄 세트 XXS~L(5 size)",
    image: "./images/hanes33.png",
    sale: 6,
    price: 47000,
    rate: 4.8,
    review: 77,
  },
  {
    id: 23,
    category: "산책용품",
    name: "딸기 백팩 하네스 세트(배냥+하네스+리드줄)(XX5~L)",
    image: "./images/hanes34.webp",
    sale: 6,
    price: 47000,
    rate: 4.8,
    review: 39,
  },
  {
    id: 24,
    category: "산책용품",
    name: "미스트엔멀로 하네스 리드줄 세트 XS~L(4 size)",
    image: "./images/hanes35.webp",
    sale: 2,
    price: 36000,
    rate: 4.8,
    review: 47,
  },
  {
    id: 25,
    category: "하우스",
    name: "펫홈 강아지 펜스 리필 2p 65cm 화이트",
    image: "./images/wall01.jpg",
    sale: 50,
    price: 15000,
    rate: 4.5,
    review: 63,
  },
  {
    id: 26,
    category: "하우스",
    name: "푸르미 매직울타리 중형 인디핑크 10p",
    image: "./images/wall02.jpg",
    price: 35400,
    rate: 4.3,
    review: 18,
  },
  {
    id: 27,
    category: "하우스",
    name: "푸르미 매직울타리 중형 아이보리 10p",
    image: "./images/wall03.jpg",
    price: 36800,
    rate: 4.5,
    review: 29,
  },
  {
    id: 28,
    category: "하우스",
    name: "푸르미 매직울타리 중형 라이트 그레이 10p",
    image: "./images/wall04.jpg",
    price: 36800,
    rate: 4.8,
    review: 32,
  },
  {
    id: 29,
    category: "의류",
    name: "M-5XL 크로플 나그랑탑 대형",
    image: "./images/poClothes01.png",
    sale: 35,
    price: 24000,
    rate: 4.5,
    review: 30,
  },
  {
    id: 30,
    category: "의류",
    name: "M-5XL 아웃사이드 쿨링 올인원",
    image: "./images/poClothes02.png",
    price: 34000,
    rate: 4.5,
    review: 43,
  },
  {
    id: 31,
    category: "의류",
    name: "S-5XL 체리 러닝수트 나시",
    image: "./images/poClothes03.png",
    price: 20000,
    rate: 5.0,
    review: 1,
  },
  {
    id: 32,
    category: "의류",
    name: "2XL-6XL 노스 폴 패딩",
    image: "./images/poClothes04.jpg",
    price: 50000,
    rate: 4.5,
    review: 12,
  },
];
