export const harnessData = [
  {
    id: 1,
    category: "하네스",
    name: "베니즈 강아지 가슴줄 베이직 하네스 옐로우",
    img: "./images/hanes01.jpg",
    rate: 3.5,
    review: 12,
    salePercent: 10,
    originalPrice: 30000,
    salePrice: 27000,
    shipping: "3,000원",
  },
  {
    id: 2,
    category: "하네스",
    name: "바잇미 캔디크레용 하네스 라이트 블루S",
    img: "./images/hanes02.jpg",
    rate: 3.5,
    review: 5,
    salePrice: 29000,
    shipping: "3,000원",
  },
  {
    id: 3,
    category: "하네스",
    name: "바잇미 캔디크레용 하네스 라이트 핑크S",
    img: "./images/hanes03.jpg",
    rate: 3.5,
    review: 9,
    salePercent: 10,
    originalPrice: 29000,
    salePrice: 23900,
    shipping: "3,000원",
  },
  {
    id: 4,
    category: "하네스",
    name: "쥬쥬베 에어매쉬 하네스 형광",
    img: "./images/hanes04.jpg",
    rate: 3.0,
    review: 3,
    salePercent: 48,
    originalPrice: 23100,
    salePrice: 12000,
    shipping: "3,000원",
  },
  {
    id: 5,
    category: "하네스",
    name: "베니즈 BENNYS 강아지 가슴줄 베이직 하네스 옐로우",
    img: "./images/hanes05.jpg",
    rate: 3.5,
    review: 9,
    salePercent: 30,
    originalPrice: 26430,
    salePrice: 18500,
    shipping: "무료배송",
  },
  {
    id: 6,
    category: "하네스",
    name: "빠른직구D 산책 야광 형광 하네스 리드줄 모음",
    img: "./images/hanes06.jpg",
    rate: 3.8,
    review: 7,
    salePercent: 30,
    originalPrice: 19290,
    salePrice: 13500,
    shipping: "3,000원",
  },
  {
    id: 7,
    category: "하네스",
    name: "커고 스태쉬 앤 대쉬 백팩 하네스 블랙",
    img: "./images/hanes07.jpg",
    rate: 5.5,
    review: 0,
    salePrice: 74800,
    shipping: "3,000원",
  },
  {
    id: 8,
    category: "하네스",
    name: "바잇미 캔디크레용 하네스 라이트 블루 S",
    img: "./images/hanes08.jpg",
    rate: 3.5,
    review: 3,
    salePercent: 30,
    salePrice: 29000,
    shipping: "3,000원",
  },
  {
    id: 9,
    category: "하네스",
    name: "커고 캐스케이드 하네스",
    img: "./images/hanes09.jpg",
    rate: 3.5,
    review: 9,
    salePercent: 20,
    originalPrice: 160000,
    salePrice: 128000,
    shipping: "무료배송",
  },
  {
    id: 10,
    category: "하네스",
    name: "헐티 콤피 하네스 가슴줄",
    img: "./images/hanes10.jpg",
    rate: 4.0,
    review: 6,
    salePercent: 22,
    originalPrice: 36000,
    salePrice: 28000,
    shipping: "3,000원",
  },
  {
    id: 11,
    category: "하네스",
    name: "패리스독 아웃도어 하네스",
    img: "./images/hanes11.jpg",
    rate: 3.5,
    review: 5,
    salePercent: 13,
    originalPrice: 17000,
    salePrice: 14500,
    shipping: "3,000원",
  },
  {
    id: 12,
    category: "하네스",
    name: "패리스독 심플 패턴 백팩 하네스 + 리드줄 세트",
    img: "./images/hanes12.jpg",
    rate: 4.5,
    review: 39,
    salePercent: 10,
    originalPrice: 15000,
    salePrice: 13000,
    shipping: "3,000원",
  },
  {
    id: 13,
    category: "하네스",
    name: "플라워 팬던트 하네스 리드줄 세트",
    img: "./images/hanes13.webp",
    rate: 3.5,
    review: 30,
    salePercent: 10,
    originalPrice: 39000,
    salePrice: 36000,
    shipping: "3,000원",
  },
  {
    id: 14,
    category: "하네스",
    name: "후르타 머드벤쳐 러쉬 강아지 리드줄",
    img: "./images/hanes14.jpg",
    rate: 4.3,
    review: 47,
    salePercent: 21,
    originalPrice: 75000,
    salePrice: 59000,
    shipping: "3,000원",
  },
  {
    id: 15,
    category: "하네스",
    name: "브레드 가방 푹백파우치 배변봉투 똥추 케이스",
    img: "./images/hanes01.jpg",
    rate: 4.5,
    review: 90,
    salePercent: 10,
    originalPrice: 16000,
    salePrice: 11700,
    shipping: "3,000원",
  },
  {
    id: 16,
    category: "하네스",
    name: "페리스독 베어턱받이 하네스 블루 리드줄 포함",
    img: "./images/hanes16.jpg",
    rate: 4.5,
    review: 39,
    salePercent: 18,
    originalPrice: 14000,
    salePrice: 11500,
    shipping: "3,000원",
  },
];

export const leashData = [
  {
    id: 1,
    category: "목줄",
    name: "쥬쥬베 LED 야광 목줄+리드줄 SET",
    img: "./images/neck01.jpg",
    rate: 4.5,
    review: 39,
    salePercent: 44,
    originalPrice: 12000,
    salePrice: 6800,
    shipping: "3,000원",
  },
  {
    id: 2,
    category: "목줄",
    name: "패츠컴퍼니 고급 목줄셋트 목걸이",
    img: "./images/neck02.jpg",
    rate: 4.5,
    review: 26,
    salePercent: 25,
    originalPrice: 9000,
    salePrice: 6800,
    shipping: "3,000원",
  },
  {
    id: 3,
    category: "목줄",
    name: "타키 자수 목줄+리드줄 SET[색상 랜덤발송]",
    img: "./images/neck03.jpg",
    rate: 4.9,
    review: 30,
    salePercent: 30,
    originalPrice: 5000,
    salePrice: 3500,
    shipping: "3,000원",
  },
  {
    id: 4,
    category: "목줄",
    name: "패리스독 고무목줄 M [색상 랜덤배송]",
    img: "./images/neck01.jpg",
    rate: 4.7,
    review: 30,
    salePrice: 7000,
    shipping: "3,000원",
  },
  {
    id: 5,
    category: "목줄",
    name: "쏘아베 솔리드 가슴줄+리드줄 세트 초코브라운 15mm",
    img: "./images/neck05.jpg",
    rate: 4.9,
    review: 15,
    salePercent: 34,
    originalPrice: 15000,
    salePrice: 9900,
    shipping: "3,000원",
  },
  {
    id: 6,
    category: "목줄",
    name: "쏘아베 솔리드 목줄+리드줄 세트 피치레드 15mm",
    img: "./images/neck01.jpg",
    rate: 4.8,
    review: 20,
    salePercent: 29,
    originalPrice: 11000,
    salePrice: 7900,
    shipping: "3,000원",
  },
  {
    id: 7,
    category: "목줄",
    name: "쏘아베 솔리드 목줄+리드줄 세트 애플그린 15mm",
    img: "./images/neck01.jpg",
    rate: 4.8,
    review: 30,
    salePercent: 29,
    originalPrice: 11000,
    salePrice: 7900,
    shipping: "3,000원",
  },
  {
    id: 8,
    category: "목줄",
    name: "에이미러브즈펫[꽃장식목줄]레드애나멜 목줄+리드줄 SET S",
    img: "./images/neck08.jpg",
    rate: 4.9,
    review: 10,
    salePrice: 39000,
    shipping: "3,000원",
  },
  {
    id: 9,
    category: "목줄",
    name: "터치독 디자인 어깨줄+리드줄 SET 15mm [색상 랜덤발송]",
    img: "./images/neck09.jpg",
    rate: 4.5,
    review: 3,
    salePercent: 40,
    originalPrice: 15000,
    salePrice: 9000,
    shipping: "3,000원",
  },
  {
    id: 10,
    category: "목줄",
    name: "쏘아베 가슴줄+리드줄 셋틑 10m/15mm(색상임의배송)",
    img: "./images/neck10.jpg",
    rate: 4.9,
    review: 89,
    salePrice: 5200,
    shipping: "3,000원",
  },
  {
    id: 11,
    category: "목줄",
    name: "쏘아베 목줄+리드줄 셋트 10mm/15mm(색상임의배송)",
    img: "./images/neck11.jpg",
    rate: 4.5,
    review: 14,
    salePrice: 4500,
    shipping: "3,000원",
  },
  {
    id: 12,
    category: "목줄",
    name: "쏘아베 대형견용 밀리터리 스타일 가슴줄 + 리드줄 SET",
    img: "./images/neck12.jpg",
    rate: 4.8,
    review: 29,
    salePercent: 20,
    originalPrice: 18000,
    salePrice: 14500,
    shipping: "3,000원",
  },
];
export const leadData = [
  {
    id: 1,
    category: "리드줄",
    name: "러쉬독 투링 야광리드줄 20mm 25mm (최대길이 3M)",
    img: "./images/lead01.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 16,
    originalPrice: 20000,
    salePrice: 16900,
    shipping: "3,000원",
  },
  {
    id: 2,
    category: "리드줄",
    name: "페로가토 룽고 롱 리드줄 4m(15mm)",
    img: "./images/lead02.jpg",
    rate: 4.9,
    review: 50,
    salePercent: 38,
    originalPrice: 12000,
    salePrice: 7500,
    shipping: "3,000원",
  },
  {
    id: 3,
    category: "리드줄",
    name: "분독 플레이리쉬 3m20cm 롱리드줄",
    img: "./images/lead03.jpg",
    rate: 4.9,
    review: 20,
    salePrice: 48000,
    shipping: "3,000원",
  },
  {
    id: 4,
    category: "리드줄",
    name: "지오디독 소프트 스냅[고리]리드줄[중/대형견종][색상선택]",
    img: "./images/lead04.jpg",
    rate: 4.9,
    review: 22,
    salePrice: 12000,
    shipping: "3,000원",
  },
  {
    id: 5,
    category: "리드줄",
    name: "금장 가죽 리드줄 [중대형견용][색상선택]",
    img: "./images/lead05.jpg",
    rate: 4.7,
    review: 12,
    salePercent: 19,
    originalPrice: 40000,
    salePrice: 32500,
    shipping: "3,000원",
  },
  {
    id: 6,
    category: "리드줄",
    name: "슈바이커트 헌팅칼라 40mm[순간방출용]",
    img: "./images/lead06.jpg",
    rate: 4.9,
    review: 5,
    salePercent: 6,
    originalPrice: 90000,
    salePrice: 85000,
    shipping: "무료배송",
  },
  {
    id: 7,
    category: "리드줄",
    name: "빅독 롱 리드줄 [2cm X 3M][색상선택]",
    img: "./images/lead07.jpg",
    rate: 4.9,
    review: 20,
    salePercent: 30,
    originalPrice: 14000,
    salePrice: 9900,
    shipping: "3,000원",
  },
  {
    id: 8,
    category: "리드줄",
    name: "빅독 롱 리드줄 [2cm X 5M] 색상선택",
    img: "./images/lead08.jpg",
    rate: 4.9,
    review: 25,
    salePercent: 22,
    originalPrice: 16000,
    salePrice: 12500,
    shipping: "3,000원",
  },
  {
    id: 9,
    category: "리드줄",
    name: "대형견용 빅트위스트로프 목줄+리드줄 세트(블루)",
    img: "./images/lead09.jpg",
    rate: 4.9,
    review: 19,
    salePercent: 34,
    originalPrice: 15000,
    salePrice: 9900,
    shipping: "3,000원",
  },
  {
    id: 10,
    category: "리드줄",
    name: "페리스독 ISPET 본드리쉬 CL0036(60cm)[색상선택]",
    img: "./images/lead10.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 19,
    originalPrice: 19000,
    salePrice: 15500,
    shipping: "3,000원",
  },
  {
    id: 11,
    category: "리드줄",
    name: "패리스독 ISPET CL0039 (120cm) 리드줄[색상선택]",
    img: "./images/lead11.jpg",
    rate: 4.9,
    review: 19,
    salePercent: 17,
    originalPrice: 12000,
    salePrice: 10000,
    shipping: "3,000원",
  },
  {
    id: 12,
    category: "리드줄",
    name: "패리스독 외출이좋아 듀얼리쉬",
    img: "./images/lead12.jpg",
    rate: 5.0,
    review: 20,
    salePercent: 19,
    originalPrice: 16000,
    salePrice: 13000,
    shipping: "무료배송",
  },
];
export const autoLeadData = [
  {
    id: 1,
    category: "자동줄",
    name: "파미고 UFO 원형 자동리드줄 3M 옐로우",
    img: "./images/autoLead01.jpg",
    rate: 5.0,
    review: 10,
    salePercent: 15,
    originalPrice: 35000,
    salePrice: 29800,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "자동줄",
    name: "파미고 UFO 원형 자동리드줄 3M 핑크",
    img: "./images/autoLead02.jpg",
    rate: 5.0,
    review: 5,
    salePercent: 15,
    originalPrice: 35000,
    salePrice: 29800,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "자동줄",
    name: "플렉시 스타일 자동줄 고광텍 테잎형 자동줄 5M",
    img: "./images/autoLead03.jpg",
    rate: 4.8,
    review: 30,
    salePercent: 10,
    originalPrice: 30000,
    salePrice: 27000,
    shipping: "3,000원",
  },
  {
    id: 4,
    category: "자동줄",
    name: "플렉시 스타일 자동줄 고광텍 테잎형 자동줄 3M",
    img: "./images/autoLead04.jpg",
    rate: 4.9,
    review: 11,
    salePercent: 10,
    originalPrice: 23000,
    salePrice: 20700,
    shipping: "3,000원",
  },
  {
    id: 5,
    category: "자동줄",
    name: "페슬러 자동리드줄 모던카키 S",
    img: "./images/autoLead05.jpg",
    rate: 4.8,
    review: 30,
    salePercent: 21,
    originalPrice: 15000,
    salePrice: 11900,
    shipping: "3,000원",
  },
  {
    id: 6,
    category: "자동줄",
    name: "페슬러 자동리드줄 모던카키 M",
    img: "./images/autoLead06.jpg",
    rate: 4.8,
    review: 15,
    salePercent: 19,
    originalPrice: 17000,
    salePrice: 12900,
    shipping: "3,000원",
  },
  {
    id: 7,
    category: "자동줄",
    name: "페슬러 자동리드줄 모던브라운 S",
    img: "./images/autoLead07.jpg",
    rate: 4.7,
    review: 9,
    salePercent: 21,
    originalPrice: 15000,
    salePrice: 11900,
    shipping: "3,000원",
  },
  {
    id: 8,
    category: "자동줄",
    name: "페슬러 자동리드줄 모던브라운 S",
    img: "./images/autoLead08.jpg",
    rate: 4.7,
    review: 5,
    salePercent: 19,
    originalPrice: 17000,
    salePrice: 12900,
    shipping: "3,000원",
  },
  {
    id: 9,
    category: "자동줄",
    name: "페슬러 자동리드줄 스카이블루 S",
    img: "./images/autoLead09.jpg",
    rate: 4.9,
    review: 16,
    salePercent: 21,
    originalPrice: 15000,
    salePrice: 11900,
    shipping: "3,000원",
  },
  {
    id: 10,
    category: "자동줄",
    name: "페슬러 자동리드줄 스카이블루 M",
    img: "./images/autoLead10.jpg",
    rate: 4.9,
    review: 6,
    salePercent: 19,
    originalPrice: 17000,
    salePrice: 12900,
    shipping: "3,000원",
  },
  {
    id: 11,
    category: "자동줄",
    name: "쥬쥬베 자동줄 3M",
    img: "./images/autoLead11.jpg",
    rate: 5.0,
    review: 25,
    salePercent: 40,
    originalPrice: 10000,
    salePrice: 6000,
    shipping: "3,000원",
  },
  {
    id: 12,
    category: "자동줄",
    name: "플렉시 바리오 자동줄 코드형 5M",
    img: "./images/autoLead12.jpg",
    rate: 5.0,
    review: 35,
    salePercent: 40,
    originalPrice: 43000,
    salePrice: 25900,
    shipping: "무료배송",
  },
];
export const lightData = [
  {
    id: 1,
    category: "라이트",
    name: "LED 무지개 불빛 라이트 목걸이",
    img: "./images/light01.jpg",
    rate: 5.0,
    review: 95,
    salePercent: 42,
    originalPrice: 20000,
    salePrice: 11500,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "라이트",
    name: "LED 무지개 불빛 라이트 목걸이 중대현경용",
    img: "./images/light02.jpg",
    rate: 5.0,
    review: 125,
    salePercent: 30,
    originalPrice: 20000,
    salePrice: 13900,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "라이트",
    name: "LED 충전식 야광라이트 목걸이",
    img: "./images/light03.jpg",
    rate: 5.0,
    review: 128,
    salePercent: 16,
    originalPrice: 9500,
    salePrice: 7900,
    shipping: "3,000원",
  },
  {
    id: 4,
    category: "라이트",
    name: "펫라이트 LED 조명",
    img: "./images/light04.jfif",
    rate: 4.9,
    review: 52,
    salePercent: 20,
    originalPrice: 49000,
    salePrice: 39000,
    shipping: "무료배송",
  },
  {
    id: 5,
    category: "라이트",
    name: "LED 야광 불빛 목줄",
    img: "./images/light05.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 1,
    originalPrice: 3900,
    salePrice: 3810,
    shipping: "3,000원",
  },
  {
    id: 6,
    category: "라이트",
    name: "LED 클립 안티 버그 라이트",
    img: "./images/light06.jpg",
    rate: 4.8,
    review: 77,
    salePercent: 55,
    originalPrice: 37000,
    salePrice: 16500,
    shipping: "무료배송",
  },
];

export const necklaceData = [
  {
    id: 1,
    category: "이름표",
    name: "문펫 꽃리스 목걸이 이름표",
    img: "./images/necklace01.jpg",
    rate: 4.9,
    review: 17,
    salePercent: 28,
    originalPrice: 5500,
    salePrice: 4000,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "이름표",
    name: "뼈다귀 실버 펜던트 이름표 목걸이",
    img: "./images/necklace02.jpg",
    rate: 4.9,
    review: 199,
    salePercent: 38,
    originalPrice: 8000,
    salePrice: 5000,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "이름표",
    name: "칼라 뼈다귀 큐빅 목걸이 이름표(블루)",
    img: "./images/necklace03.jpg",
    rate: 4.8,
    review: 24,
    salePercent: 17,
    originalPrice: 6000,
    salePrice: 5000,
    shipping: "무료배송",
  },
  {
    id: 4,
    category: "이름표",
    name: "문펫 실버 강아지모양 이름표",
    img: "./images/necklace04.jpg",
    rate: 4.9,
    review: 170,
    salePercent: 17,
    originalPrice: 6000,
    salePrice: 5000,
    shipping: "무료배송",
  },
  {
    id: 5,
    category: "이름표",
    name: "뽀글이 이름표",
    img: "./images/necklace05.jpg",
    rate: 4.9,
    review: 5,
    salePrice: 10000,
    shipping: "3,000원",
  },
  {
    id: 6,
    category: "이름표",
    name: "ALWAYS WITH 실버 볼체인 이름표 목걸이",
    img: "./images/necklace06.jpg",
    rate: 4.9,
    review: 166,
    salePercent: 15,
    originalPrice: 20000,
    salePrice: 16900,
    shipping: "무료배송",
  },
  {
    id: 7,
    category: "이름표",
    name: "하트원형 POU89 이름표 목걸이",
    img: "./images/necklace07.jpg",
    rate: 4.8,
    review: 17,
    salePercent: 29,
    originalPrice: 12000,
    salePrice: 8500,
    shipping: "3,000원",
  },
  {
    id: 8,
    category: "이름표",
    name: "MAXIMA 써지컬스틸 하트 네임택 336XA",
    img: "./images/necklace08.jpg",
    rate: 4.9,
    review: 12,
    salePercent: 32,
    originalPrice: 10000,
    salePrice: 6800,
    shipping: "3,000원",
  },
  {
    id: 9,
    category: "이름표",
    name: "산책와펜 네임택 강아지 인식표",
    img: "./images/necklace09.jpg",
    rate: 4.9,
    review: 25,
    salePercent: 62,
    originalPrice: 15900,
    salePrice: 5900,
    shipping: "무료배송",
  },
  {
    id: 10,
    category: "이름표",
    name: "반려동물 외출용 가죽 인식표",
    img: "./images/necklace10.jpg",
    rate: 4.9,
    review: 165,
    salePercent: 60,
    originalPrice: 9600,
    salePrice: 3800,
    shipping: "3,000원",
  },
];

export const cageData = [
  {
    id: 1,
    category: "이동장",
    name: "딩동펫 이동장 항공켄넬 450",
    img: "./images/cage01.jpg",
    rate: 4.8,
    review: 35,
    salePrice: 53200,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "이동장",
    name: "딩동펫 더블캐리 이동장 켄넬 블루 M",
    img: "./images/cage02.jpg",
    rate: 4.9,
    review: 85,
    salePrice: 27200,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "이동장",
    name: "아이리스 에어트래블 항공 컨넬 화이트 특대형 870",
    img: "./images/cage03.jpg",
    rate: 4.9,
    review: 5,
    salePrice: 22900,
    shipping: "무료배송",
  },
  {
    id: 4,
    category: "이동장",
    name: "아이리스 에어트래블 항공 컨넬 화이트 대형 670",
    img: "./images/cage04.jpg",
    rate: 4.9,
    review: 4,
    salePrice: 12500,
    shipping: "무료배송",
  },
  {
    id: 5,
    category: "이동장",
    name: "아이리스 에어트래블 항공 컨넬 브라운 특대형 870",
    img: "./images/cage05.jpg",
    rate: 4.9,
    review: 5,
    salePrice: 22900,
    shipping: "무료배송",
  },
  {
    id: 6,
    category: "이동장",
    name: "아이리스 에어트래블 항공 컨넬 브라운 대형 670",
    img: "./images/cage06.jpg",
    rate: 4.9,
    review: 4,
    salePrice: 12500,
    shipping: "무료배송",
  },
  {
    id: 7,
    category: "이동장",
    name: "리니펫 반려동물캔낼 블랙이동장",
    img: "./images/cage07.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 20,
    originalPrice: 27900,
    salePrice: 22320,
    shipping: "무료배송",
  },
  {
    id: 8,
    category: "이동장",
    name: "리니펫 스틸블루/다크브라운 이동장",
    img: "./images/cage08.jpg",
    rate: 4.9,
    review: 35,
    salePercent: 20,
    originalPrice: 49400,
    salePrice: 39520,
    shipping: "무료배송",
  },
  {
    id: 9,
    category: "이동장",
    name: "리니펫 브라운 펫이동장",
    img: "./images/cage09.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 20,
    originalPrice: 31800,
    salePrice: 25440,
    shipping: "무료배송",
  },
  {
    id: 10,
    category: "이동장",
    name: "리니펫 펫이동장 민트",
    img: "./images/cage10.jpg",
    rate: 4.8,
    review: 5,
    salePercent: 20,
    originalPrice: 31800,
    salePrice: 25440,
    shipping: "무료배송",
  },
  {
    id: 11,
    category: "이동장",
    name: "리니펫 펫이동장 다크그레이",
    img: "./images/cage11.jpg",
    rate: 4.6,
    review: 8,
    salePercent: 20,
    originalPrice: 31800,
    salePrice: 25440,
    shipping: "무료배송",
  },
  {
    id: 12,
    category: "이동가방",
    name: "리니펫 심플 펫 펫이동장 민트",
    img: "./images/cage10.jpg",
    rate: 4.8,
    review: 2,
    salePercent: 20,
    originalPrice: 33800,
    salePrice: 27040,
    shipping: "무료배송",
  },
];

export const bagData = [
  {
    id: 1,
    category: "이동가방",
    name: "리니펫 밀리터리 이동가방",
    img: "./images/bag01.jpg",
    rate: 5.0,
    review: 2,
    salePercent: 20,
    originalPrice: 71300,
    salePrice: 57040,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "이동가방",
    name: "리니펫 쏘아베 이동가방",
    img: "./images/bag02.jpg",
    rate: 5.0,
    review: 1,
    salePercent: 20,
    originalPrice: 43800,
    salePrice: 35040,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "이동가방",
    name: "리니펫 에그 크로스백 L 포대기 앞가방",
    img: "./images/bag03.jpg",
    rate: 4.9,
    review: 72,
    salePercent: 20,
    originalPrice: 58600,
    salePrice: 46880,
    shipping: "무료배송",
  },
  {
    id: 4,
    category: "이동가방",
    name: "리니펫 패리스독 피너츠 슬링백",
    img: "./images/bag04.jpg",
    rate: 5.0,
    review: 8,
    salePercent: 20,
    originalPrice: 51250,
    salePrice: 41000,
    shipping: "무료배송",
  },
  {
    id: 5,
    category: "이동가방",
    name: "리니펫 패리스독 피너츠 슬링 베이지 이동가방",
    img: "./images/bag05.jpg",
    rate: 5.0,
    review: 42,
    salePercent: 20,
    originalPrice: 36250,
    salePrice: 29000,
    shipping: "무료배송",
  },
  {
    id: 6,
    category: "이동가방",
    name: "리니펫 패리스독 피너츠 슬링백 이동가방",
    img: "./images/bag06.jpg",
    rate: 5.0,
    review: 19,
    salePercent: 20,
    originalPrice: 60000,
    salePrice: 48000,
    shipping: "무료배송",
  },
  {
    id: 7,
    category: "이동가방",
    name: "리니펫 도기프랜드 투스백 이동가방",
    img: "./images/bag07.jpg",
    rate: 4.9,
    review: 6,
    salePercent: 20,
    originalPrice: 27200,
    salePrice: 21760,
    shipping: "무료배송",
  },
  {
    id: 8,
    category: "가방",
    name: "리니펫 베이지 체크 이동가방",
    img: "./images/bag08.jpg",
    rate: 4.8,
    review: 65,
    salePercent: 20,
    originalPrice: 30200,
    salePrice: 24160,
    shipping: "무료배송",
  },
  {
    id: 9,
    category: "이동가방",
    name: "리니펫 펫라인 신형 체크 이동가방",
    img: "./images/bag09.jpg",
    rate: 4.7,
    review: 27,
    salePercent: 20,
    originalPrice: 31200,
    salePrice: 24960,
    shipping: "무료배송",
  },
  {
    id: 10,
    category: "이동가방",
    name: "리니펫 패리스독 월튼 펫 백 핑크",
    img: "./images/bag10.jpg",
    rate: 4.8,
    review: 17,
    salePercent: 20,
    originalPrice: 57500,
    salePrice: 46000,
    shipping: "무료배송",
  },
];

export const cartData = [
  {
    id: 1,
    category: "유모차",
    name: "멍묘인 무소음 유모차 개모차",
    img: "./images/cart01.jpg",
    rate: 4.9,
    review: 3,
    salePercent: 40,
    originalPrice: 199000,
    salePrice: 119000,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "유모차",
    name: "폼포라펫 클래식 웨건 딥블랙 저상형 개모차",
    img: "./images/cart02.jfif",
    rate: 5.0,
    review: 1,
    salePercent: 27,
    originalPrice: 890000,
    salePrice: 649000,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "유모차",
    name: "베베로드 TT 프리미엄 분리형 접이식 캐리어",
    img: "./images/cart03.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 22,
    originalPrice: 270000,
    salePrice: 210000,
    shipping: "무료배송",
  },
  {
    id: 4,
    category: "유모차",
    name: "모나크 프리미엄 골드 유모차 FS1616",
    img: "./images/cart04.jpg",
    rate: 5.0,
    review: 1,
    salePercent: 7,
    originalPrice: 420000,
    salePrice: 390000,
    shipping: "무료배송",
  },
  {
    id: 5,
    category: "유모차",
    name: "아로아 퀵폴딩 유모차",
    img: "./images/cart05.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 21,
    originalPrice: 378000,
    salePrice: 298000,
    shipping: "무료배송",
  },
  {
    id: 6,
    category: "유모차",
    name: "개달당 코코 라이너쿠션 범퍼패드 개모차",
    img: "./images/cart06.jpg",
    rate: 5.0,
    review: 3,
    salePercent: 11,
    originalPrice: 890000,
    salePrice: 699000,
    shipping: "무료배송",
  },
  {
    id: 7,
    category: "유모차",
    name: "레드퍼피 트레블러 웨건",
    img: "./images/cart07.jpg",
    rate: 5.0,
    review: 0,
    salePrice: 125000,
    shipping: "무료배송",
  },
  {
    id: 8,
    category: "유모차",
    name: "버디두기 라이더 핏츠 분리형 유모차",
    img: "./images/cart08.jpg",
    rate: 5.0,
    review: 1,
    salePercent: 34,
    originalPrice: 289000,
    salePrice: 189000,
    shipping: "무료배송",
  },
  {
    id: 9,
    category: "유모차",
    name: "펫니즈 보랄 유모차 PNZ-DS01",
    img: "./images/cart09.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 30,
    originalPrice: 302900,
    salePrice: 212000,
    shipping: "무료배송",
  },
  {
    id: 10,
    category: "유모차",
    name: "와이타운 유모차 3colors",
    img: "./images/cart10.jpg",
    rate: 5.0,
    review: 0,
    salePrice: 119000,
    shipping: "무료배송",
  },
];

export const carData = [
  {
    id: 1,
    category: "차량용",
    name: "크리미 강아지 카시트 2size 3colors",
    img: "./images/car01.jpg",
    rate: 4.9,
    review: 43,
    salePercent: 58,
    originalPrice: 59900,
    salePrice: 24900,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "차량용",
    name: "알러프리 카시트 드라이빙킷 2size",
    img: "./images/car02.jpg",
    rate: 5.0,
    review: 5,
    salePercent: 33,
    originalPrice: 119000,
    salePrice: 79000,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "차량용",
    name: "초코펫하우스 로얄 사각 카시트 4colors",
    img: "./images/car03.jpg",
    rate: 4.9,
    review: 17,
    salePercent: 37,
    originalPrice: 95000,
    salePrice: 59800,
    shipping: "무료배송",
  },
  {
    id: 4,
    category: "차량용",
    name: "세븐펫 구름 카시트 4colors",
    img: "./images/car04.jpg",
    rate: 5.0,
    review: 69,
    salePercent: 31,
    originalPrice: 69000,
    salePrice: 47200,
    shipping: "무료배송",
  },
  {
    id: 5,
    category: "차량용",
    name: "율리 베이직 카시트 2size 4colors",
    img: "./images/car05.jpg",
    rate: 4.8,
    review: 1300,
    salePercent: 55,
    originalPrice: 79900,
    salePrice: 35000,
    shipping: "무료배송",
  },
  {
    id: 6,
    category: "차량용",
    name: "바리스타 펫테일 카시트 대형 자동차",
    img: "./images/car06.jpg",
    rate: 4.9,
    review: 22,
    salePrice: 87900,
    shipping: "무료배송",
  },
  {
    id: 7,
    category: "차량용",
    name: "스윗픽 빠방 카시트 2 colors",
    img: "./images/car07.jpg",
    rate: 4.7,
    review: 10,
    salePercent: 22,
    originalPrice: 115000,
    salePrice: 89000,
    shipping: "무료배송",
  },
  {
    id: 8,
    category: "차량용",
    name: "3in1 방수 올커버 분리형 쿠션",
    img: "./images/car08.jpg",
    rate: 4.9,
    review: 1,
    salePercent: 38,
    originalPrice: 69900,
    salePrice: 42900,
    shipping: "무료배송",
  },
  {
    id: 9,
    category: "차량용",
    name: "레드퍼피 카트라 카시트 중형",
    img: "./images/car09.jpg",
    rate: 5.0,
    review: 0,
    salePrice: 49000,
    shipping: "무료배송",
  },
  {
    id: 10,
    category: "차량용",
    name: "올치 캐리어 카시트 소프트 드라이빙킷 3colors",
    img: "./images/car01.jpg",
    rate: 4.9,
    review: 97,
    salePercent: 15,
    originalPrice: 79000,
    salePrice: 67100,
    shipping: "무료배송",
  },
];

export const lipsData = [
  {
    id: 1,
    category: "입마개",
    name: "멍스크 KF 마스크 강아지 입마개 3ea",
    img: "./images/lips01.jfif",
    rate: 3.5,
    review: 2,
    salePercent: 4,
    originalPrice: 11800,
    salePrice: 11180,
    shipping: "무료배송",
  },
  {
    id: 2,
    category: "입마개",
    name: "블리 퍼그 보스턴테리어 프렌치불독 시츄 단두종 납작코 입마개",
    img: "./images/lips02.jfif",
    rate: 4.9,
    review: 4,
    salePercent: 45,
    originalPrice: 20830,
    salePrice: 11300,
    shipping: "무료배송",
  },
  {
    id: 3,
    category: "입마개",
    name: "쏘울펫 입마개 짖음 방지기 대형견",
    img: "./images/lips03.jpg",
    rate: 5.0,
    review: 5,
    salePrice: 8900,
    shipping: "3,000원",
  },
  {
    id: 4,
    category: "입마개",
    name: "딩동펫 메쉬 소프트입마개",
    img: "./images/lips04.jpg",
    rate: 4.9,
    review: 9,
    salePercent: 62,
    originalPrice: 15800,
    salePrice: 5900,
    shipping: "무료배송",
  },
  {
    id: 5,
    category: "입마개",
    name: "포시립 원버튼 메쉬 입마개",
    img: "./images/lips05.jpg",
    rate: 4.5,
    review: 3,
    salePercent: 47,
    originalPrice: 15000,
    salePrice: 7900,
    shipping: "무료배송",
  },
  {
    id: 6,
    category: "입마개",
    name: "예홈 목줄 입마개",
    img: "./images/lips06.jpg",
    rate: 5.0,
    review: 0,
    salePercent: 4,
    originalPrice: 20900,
    salePrice: 19900,
    shipping: "무료배송",
  },
  {
    id: 7,
    category: "입마개",
    name: "애구애구 대형견 입마개(M/L/XL/2XL)",
    img: "./images/lips07.jpg",
    rate: 5,
    review: 1,
    salePercent: 30,
    originalPrice: 15000,
    salePrice: 10500,
    shipping: "무료배송",
  },
  {
    id: 8,
    category: "입마개",
    name: "에코벨 실리콘 입마개 소형견 오리마스크",
    img: "./images/lips08.jpg",
    rate: 5.0,
    review: 1,
    salePercent: 59,
    originalPrice: 5900,
    salePrice: 2400,
    shipping: "3,000원",
  },
  {
    id: 9,
    category: "입마개",
    name: "애구애구 짖음방지 매쉬 마스크",
    img: "./images/lips09.jpg",
    rate: 4.9,
    review: 2,
    salePercent: 49,
    originalPrice: 5000,
    salePrice: 2520,
    shipping: "3,000원",
  },
  {
    id: 10,
    category: "입마개",
    name: "딩동펫 실리콘 입마개",
    img: "./images/lips10.jpg",
    rate: 5.0,
    review: 1,
    salePercent: 50,
    originalPrice: 19800,
    salePrice: 9900,
    shipping: "무료배송",
  },
];

export function fetchCategoryData(category) {
  return new Promise((resolve) => {
    setTimeout(() => {
      switch (category) {
        case "목줄":
          resolve(leashData);
          break;
        case "하네스":
          resolve(harnessData);
          break;
        case "리드줄":
          resolve(leadData);
          break;
        case "자동줄":
          resolve(autoLeadData);
          break;
        case "라이트":
          resolve(lightData);
          break;
        case "이름표":
          resolve(necklaceData);
          break;
        case "이동장":
          resolve(cageData);
          break;
        case "이동가방":
          resolve(bagData);
          break;
        case "유모차":
          resolve(cartData);
          break;
        case "차량용":
          resolve(carData);
          break;
        case "입마개":
          resolve(lipsData);
          break;
        default:
          resolve([]);
      }
    }, 100);
  });
}
